package sqliteDatabase;



public class WordData {
	
	// AF : Represents a certain English language word with a
	// generated difficulty
	
	private long id;
	private String word;
	
	// gets the autogenerated id
	public long getId() {
		return id;
	}
	
	// set the id
	public void setId(long id) {
		this.id = id;
	}
	
	// get the word string
	public String getWord() {
		return word;
	}
	
	// set the word
	public void setWord(String word) {
		this.word = word;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (obj == this) {
			return true;
		}
		if (obj == null || obj.getClass() != this.getClass()) {
			return false;
		}
		
		WordData other = (WordData) obj;
		return this.word == other.word;
	}
	
	@Override
	public int hashCode() {
		return word.hashCode();
	}
	
	// how to display the worddata
	@Override
	public String toString() {
		return word;
	}
}
